# Generated by Django 4.2.6 on 2023-10-29 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_it_teacher_skills_remove_student_rating_and_more'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.FileField(blank=True, upload_to='content'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authentication.teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='techs',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='course',
            name='details',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
