# Generated by Django 4.2.6 on 2023-10-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='it',
            new_name='skills',
        ),
        migrations.RemoveField(
            model_name='student',
            name='rating',
        ),
        migrations.AlterField(
            model_name='student',
            name='fullname',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='fullname',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
